### PR TITLE
use dedicated container to run veracode

### PR DESCRIPTION
**Pull request by simao**

### CODE REVIEW

**Comment by simao** [comment]
Depends on https://github.com/advancedtelematic/infra-dockerfiles/pull/55/

**Comment by zabbal** [comment]
Looks good - I suggest to test this in gitlab before merging it. Once the corresponding changes in advancedtelematic/infra-dockerfiles#55 are merged.

**Comment by zabbal** [comment]
Let's keep this open until advancedtelematic/infra-dockerfiles#55 is resolved and merged. After that we can properly test it in a separate branch with gitlab pipeline.

**Comment by zabbal** [comment]
Blocked until schedule is restored for ota-tuf in gitlab

**Pull request merged**
